api_version:    go1
runtime:        go
threadsafe:     true # unnecessary?

handlers:

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /
  script: _go_app
  secure: always
