service:     teraconnect-authoring
api_version: go1
runtime:     go
threadsafe:  true # unnecessary?

handlers:

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /
  static_files: static/teraconnect/index.html
  upload: static/teraconnect/index.html
  secure: always

- url: /robots.txt$
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /(.*\.(js|css|png|jpg|map|woff2|wasm))$
  static_files: static/teraconnect/\1
  upload: static/teraconnect/.*\.(js|css|png|jpg|map|woff2|wasm)$
  secure: always

- url: /.*
  static_files: static/teraconnect/index.html
  upload: static/teraconnect/index.html
  secure: always

skip_files:
  - ^(.*/)?\..*$
