service:     teraconnect-authoring
api_version: go1
runtime:     go
threadsafe:  true # unnecessary?

handlers:

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /.*
  static_files: static/teraconnect/index.html
  upload: static/teraconnect/index.html
  secure: always
